notebook:
    continue: true
    source_base: src
    output_base: docs
    html_dir: _build/html
    template: docs/jupyter_notebook_sphinx.tpl
    directories:
        - source: workshops
          output: tutorials
          match: Solution
        - source: surrogate
          output: surrogate
        - source: properties/Workshop_Module_2_DMF
          output: properties/Workshop_DMF
          match: Solution
sphinx:
    args: "-b html -T docs docs/_build/html"
    error_file: sphinx-errors.txt