notebook:
    continue: true
    source_base: src
    output_base: docs
    html_dir: build
    directories:
        - source: workshops
          output: tutorials
          match: Solution
        - source: surrogate
          output: surrogate
        - source: properties/Workshop_Module_2_DMF
          output: properties/Workshop_DMF
          match: Solution
sphinx:
    args: "-b html -T docs docs/build"
    error_file: sphinx-errors.txt