name: Run examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  examples:
    name: Build examples (py${{ matrix.python-version }}/${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      # if fail-fast == true (the default), jobs for the remaining values in the matrix are cancelled
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.7'
        os:
          - ubuntu-18.04
          - windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install own dependencies
      run: |
        echo $PWD
        ls -lh .
        python -m pip install --progress-bar=off -r requirements.txt
    - name: Install IDAES
      run: |
        python -m pip install --progress-bar=off git+https://github.com/idaes/idaes-pse
        idaes --version
    - name: Install IDAES extensions
      run: |
        idaes get-extensions --platform ubuntu1804
    - name: Run non-integration tests
      run: |
        pytest --verbose -m "not integration" tests/
    - name: Save Sphinx build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sphinx-errors
        path: sphinx-errors.txt
    - name: Save test build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-errors
        path: ci-test-errors.txt
